### PR TITLE
Add strict TypeScript config

### PR DESCRIPTION
**Pull request by alecmev**
https://github.com/typescript-eslint/typescript-eslint/pull/4706

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Interesting.

For this project I’ve always taken the approach of only ever including recommended configs, so as not to completely overwhelm people with new rules. I’m aiming for a balanced set of rules for the average developer, rather the the strictest set for the power user, if that makes sense. 

I’ve used this now at a few consultancy clients and what I normally do is create a very simple company eslint config that loads this in and then has a few small adaptations for the target code base. 

I think if you want to include this for your projects, that might be a better approach, rather than add it here for everyone.

**Comment by alecmev** [comment]
I understand and agree with your rationale about not enabling it for all consumers. What do you think about using a heuristic? Maybe looking up if any of the "strict" family settings are in `tsconfig.json`, and enabling it only then?

Thank you for making this, by the way!

**Comment by davidjbradshaw** [comment]
Sorry for slow reply, I've been ill. That sounds reasonable if you want to give it a go.

**Comment by alecmev** [comment]
No worries at all! Wish you quick recovery, David.

I moved on to an in-house config a while ago. I think this project is a good idea, but it needs more work to be truly "batteries included". As-is, I had to maintain an increasingly large list of overrides, unfortunately. Not saying it's on you, it appears to serve you well, and everything else is just an extra, thanks for sharing it.

I'll close this PR, as it's definitely stale.

**Pull request closed without merging**
